macournoyer/thin

thin.gemspec
Thin depends on eventmachine which fails to build on `ruby >= 2.2` prior to `1.0.4`, [related issue][1].
This PR updates eventmachine dependency to `~> 1.0.4`
[1]: https://github.com/eventmachine/eventmachine/issues/553
=> Update eventmachine for ruby 2.2.0

lib/thin/backends/base.rb
Hi! When I am reading thin source code for learning, I found a typo in documentation.
=> Fix doc typo

lib/thin/daemonizing.rb
Hi,
I've noticed, that if I restart thin while it handles a connection, it doesn't send response back.
Example app:
```
require 'thin'
app = proc do |env|
body = ["hi!"]
sleep 10
[200, { 'Content-Type' => 'text/html' }, body]
end
run app
```
Then if I do ```thin -d start```, then ```curl localhost:3000``` and then immediately ```thin -d restart```, thin will wait 10 seconds while the work is in progress and then will go to restart. But no response will be sent back:
```
$ curl localhost:3000
curl: (52) Empty reply from server
```
I am not sure this is the right approach, but if I call ```exit!``` in the next tick, all works correctly.
```
$ curl localhost:3000
hi!
```
=> When restarting, exit on a next tick so we can send response back to a client

lib/thin/server.rb
When I try calling it via `Rack::Server.new(server: "thin")`, there seems to be no way to specify request timeout.
This change will let us use `timeout` option on `Rack::Server.new`. The usage is like below:
```
Rack::Server.new(server: "thin", timeout: 180).start
```
=> add :timeout option for Rack::Server.new

lib/thin/logging.rb
`trace_message` is issuing many warnings in the Rack tests.  Initializing `@trace_logger` to nil eliminates those warnings.
=> initialize `@trace_logger` to nil

lib/thin/logging.rb
If an exception object is not passed to `log_error`, ensure that `log_msg` is built anyway. Otherwise, there is no way to log at `Logger::ERROR` level.
Resolves #248
=> Fix for issue 248

lib/thin/controllers/service.rb
Emacs creates backup files by default whenever you change a file. These files end with a "~" e.g. "config.yml~". Thin does not ignore them but it should.
If i have a config.yml and edit it to change the number of servers i end up with a config.yml and a config.yml~ which are both used by thin.
=> ignore emacs backup files in config_path

lib/thin/server.rb
Just a few minor changes to neaten the documentation up a little.
=> Fix pluralization and typos in docs

lib/thin/request.rb
These changes are the minimal ones necessary to allow Roda's specs
to pass.  There may well be other changes that are required.
=> Work with ruby 2.3's --enable-frozen-string-literal

lib/thin/backends/tcp_server.rb
This PR updates the TCP/IP backend to report the anonymous port and the address the actual service socket was bound to.
=> TCP/IP Backend reports incorrect port when asked to bind to 0

ext/thin_parser/parser.c, ext/thin_parser/parser.rl
Hello there,
i have had a code-reading session, during which i've noticed that "cs" variable became orphan after [this commit](https://github.com/macournoyer/thin/commit/d5b523e6fda527588c690b5f37c25893c1cd0701#diff-c93c578d3adba198316570e4199fb804L140)
sorry in advance if i'm wrong.
=> Don't need "int cs" variable here

spec/controllers/service_spec.rb
Hi,
I am using Fedora 23.
And I got test failure in my environment.
Then I modified the test case a little bit to pass the test suite.
```
$ ruby -v
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]
$ bundle install --path vendor/bundle
$ bundle exec rake spec
...
1)
'Thin::Controllers::Service should create /etc/init.d/thin file when calling install' FAILED
expected "#!/bin/sh\n### BEGIN INIT INFO\n# Provides:          thin\n# Required-Start:    $local_fs $remote_fs\n# Required-Stop:     $local_fs $remote_fs\n# Default-Start:     2 3 4 5\n# Default-Stop:      S 0 1 6\n# Short-Description: thin initscript\n# Description:       thin\n### END INIT INFO\n\n# Original author: Forrest Robertson\n\n# Do NOT \"set -e\"\n\nDAEMON=thin\nSCRIPT_NAME=tmp/sandbox/etc/rc.d/thin\nCONFIG_PATH=tmp/s …
```
=> Fix test suite for the case /etc/rc.d exists.

lib/thin/connection.rb
... in threaded mode
Fixes #307
=> Ensure the request is closed in the same thread as the app

lib/thin/server.rb
Fixnum and Bignum are being deprecated in ruby version 2.4
https://bugs.ruby-lang.org/issues/12739, use 0.class to
handle the transition
=> Fixnum is deprecated in upcoming ruby version

thin.gemspec
Makes it easy to programatically find the source code and changelog for `thin`, using the rubygems API. More details on the direction of travel for gemspecs is [here](https://github.com/rubygems/rubygems.org/issues/1127) and [here](https://github.com/rubygems/rubygems.org/pull/1234), and the current state is [here](https://github.com/rubygems/rubygems/blob/master/lib/rubygems/specification.rb).
(My interest in this is so that [Dependabot](https://dependabot.com) can find a link to the `thin` source code when it creates PRs. Without that link, we generate PRs like [this one](https://github.com/greysteil/onebody/pull/20), rather than PRs like [this one](https://github.com/greysteil/onebody/pull/12).)
=> Add source code and changelog links to gemspec

ext/thin_parser/parser.h
https://github.com/macournoyer/thin/commit/d5b523e6fda527588c690b5f37c25893c1cd0701 renamed the parser functions to include a `thin_` prefix as a namespace, but did not update the parser header file. This did not cause any problems for a long time because `implicit-function-declaration` was just a warning previously, but [Xcode 12 has made it an error](https://developer.apple.com/documentation/xcode-release-notes/xcode-12-beta-release-notes#Updates-in-Xcode-12-Beta) (second bullet under Apple Clang Compiler > Resolved):
> Clang now reports an error when you use a function without an explicit declaration when building C or Objective-C code for macOS (-Werror=implicit-function-declaration flag is on). This additional error detection unifies Clang’s behavior for iOS/tvOS and macOS 64-bit …
=> fix: update parser header file with namespaced functions

lib/thin/backends/base.rb
Specifically `@running`, but it seems sensible to also init `@stopping` since they are a bit of a tandem.
=> Silence Ruby warnings for un-initialized ivars

spec/runner_spec.rb
Ruby changed the way Kernel#warn reports the error [1], but mocking the
method on the class, which is calling it, should be universal [2].
[1] https://bugs.ruby-lang.org/issues/12944
[2] https://www.reddit.com/r/ruby/comments/2nki9q/rspec_how_do_you_mock_or_stub_kernel_methods_like/
=> Mock Kernel.warn in Ruby 2.5 compatible way.

Gemfile, spec/backends/swiftiply_client_spec.rb, spec/backends/unix_server_spec.rb, spec/connection_spec.rb, spec/controllers/controller_spec.rb, spec/controllers/service_spec.rb, spec/daemonizing_spec.rb, spec/logging_spec.rb, spec/request/processing_spec.rb, spec/runner_spec.rb, spec/server/unix_socket_spec.rb, spec/spec_helper.rb, tasks/spec.rake, thin.gemspec
I would send patch to use RSpec3.
Let me check the result of Travis with this PR, as I fixed mostly, but still not perfect (2 failures)
I want to know whether the 2 failures depend on Ruby version or not, as I am using new version Ruby 2.4.0.
```
$ ruby -v
ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-linux]
$ bundle -v
Bundler version 1.14.3
$ bundle install --path vendor/bundle
$ bundle list
Gems included by the bundle:
* bundler (1.14.3)
* daemons (1.2.4)
* diff-lcs (1.3)
* eventmachine (1.2.3)
* rack (2.0.1)
* rake (12.0.0)
* rake-compiler (1.0.3)
* rspec (3.5.0)
* rspec-core (3.5.4)
* rspec-expectations (3.5.0)
* rspec-mocks (3.5.0)
* rspec-support (3.5.0)
* thin (1.7.0)
$ bundle exec rake spec
...
[2017-03-02T22:11:15.056429 #17551]  INFO -- : Hey
[2017-03-02T22:11:15.065435 …
```
=> Support RSpec 3

lib/thin/daemonizing.rb
When running Thin as another user, $USER and $HOME are set using the same parameters as when setting the UID and GID.
Resolves #275
=> Set $USER and $HOME when running as another user

lib/thin/request.rb, spec/connection_spec.rb, spec/request/parser_spec.rb
If a request contains a lying `Content-Length` header and has a body that vastly exceeds the specified size then thin will invoke the connected app several times. Precisely, it will invoke the app once when the first chunk brings the body size above the specified `Content-Length` size. This will cause `Request#parse` to respond `true`. It will then invoke the app for every additional chunk received as `Request#parse` continues to respond `true`.
I could see this being fixed in `Request#parse` or `Connection#receive_data`. I chose the former, but included specs for both `Request` and `Connection` which demonstrate the bug when my change is not present.
Raising `InvalidRequest` could be done earlier and most strictly if it was placed later in `Request#parse` so it checks body size after the …
=> Fix duplicate invalid requests

spec/server_spec.rb
This test recently started to fail on Fedora. I suspect that either Kernel or systemd increased RLIMIT_NOFILE by default to 512k.
There should probably be additional logic, which would initialize the
`maximum_connections` variable I refactored. `prlimit` can display the actual value.
=> Fix maximum_connections limiting test.

lib/thin/headers.rb, spec/headers_spec.rb
Ignore any response header with `\r` or `\n` in their value.
See https://github.com/advisories/GHSA-84j7-475p-hp8v
=> Fix possible HTTP Response Splitting

spec/spec_helper.rb
On Ubuntu Impish (development version), we're currently facing a
problem where thin's testsuite fails when it runs on an armhf system.
After some investigation, I noticed that the reason for this failure
was that the server was still running even after the loop on
`spec/spec_helper.rb:stop_server`.
Given that the loop is actively checking to see if the server has
stopped, I'd like to propose that the timeout be increased from 1
second to 10 seconds.  Although I'm not a fan of the
"let's-just-increase-the-timeout" type of solutions, in this
particular case I think it's justified and makes sense (1 second may
indeed be too quick for the server to properly stop).
=> Increase timeout when checking for server stop

lib/thin/connection.rb, spec/connection_spec.rb
Fixes #357 
Seems like there's already code in `connection.rb` to fix up the env when using ssl  (`rack.url_scheme` is always "http" after running through `thin_parser`).  This fixes up the `SERVER_PORT` as well.
=> Fix up SERVER_PORT when using ssl

.github/workflows/test.yml, gems/rack-head.rb, gems/rack-v3.rb, lib/rack/handler/thin.rb, lib/rackup/handler/thin.rb, lib/thin/rackup/handler.rb
Hello,
following what have been done in https://github.com/macournoyer/thin/pull/399 I was trying to see if I was able to upgrade resque ( https://github.com/resque/resque/pull/1912 ) to support rack 3.x. As it wasn't working, digging a little I think `thin` is missing one last bit in order to be able to work both with rack 2/3 and with/without rackup gem. I've taken inspiration on what has been done in puma https://github.com/puma/puma/pull/3532.
Thanks,
Andrea
=> Support rack 3.x and rackup

lib/thin/env.rb, lib/thin/request.rb, spec/request/parser_spec.rb
@ioquatix if I understood correctly your comment in the other [PR](https://github.com/macournoyer/thin/pull/435#issuecomment-2646640616) that should be it. 😄 
Regarding adding tests on `rack-conform`, I've looked at the code and my idea was to add a test Middleware to intercept environment. What do you think?
=> Rack 3 no longer required environments

spec/daemonizing_spec.rb
```
> bundle exec rspec spec/daemonizing_spec.rb -fd
Daemonizing
should have a pid file
should create a pid file
should redirect stdio to a log file
should change privilege
/Users/samuel/.gem/ruby/3.4.4/gems/daemons-1.4.1/lib/daemons/daemonize.rb:157:in 'IO#reopen': No such file or directory @ rb_io_reopen - /var/folders/cm/p8lkj40s0vz_vgx_b5df9dkm0000gn/T/d20250621-29968-3zseqz/test_server.log (Errno::ENOENT)
from /Users/samuel/.gem/ruby/3.4.4/gems/daemons-1.4.1/lib/daemons/daemonize.rb:157:in 'Daemonize.redirect_io'
from /Users/samuel/.gem/ruby/3.4.4/gems/daemons-1.4.1/lib/daemons/daemonize.rb:112:in 'Daemonize.daemonize'
from /Users/samuel/Developer/macournoyer/thin/lib/thin/daemonizing.rb:58:in 'Thin::Daemonizable#daemonize'
from …
```
=> Fix "No such file or directory @ rb_io_reopen" error from test.
